main_menu/urls.py
from django.urls import path
from .views import *
from .serializer import RentSaleSerializer

urlpatterns = [
    path('', Menu.as_view(), name='all_objects'),
    path('contacts/', contacts, name='contacts'),
    path('sale/', Sale.as_view(), name='sale_list'),
    path('rent/', Rent.as_view(), name='rent_list'),
    path('about_us/', about_us, name='about_us'),
    path('medical_insurance/', medical_insurance, name='medical_insurance'),
    path('resident_card/', resident_card, name='resident_card'),
    path('terms_of_use/', terms_of_use, name='terms_of_use'),
    path('privacy_policy/', privacy_policy, name='privacy_policy'),
    path('frequently_asked_questions/', frequently_asked_questions, name='frequently_asked_questions'),
    path('citizenship/', citizenship, name='citizenship'),
    path('detail/<int:pk>', ObjectDetail.as_view(), name='detail_view'),
    path('client_request/', ClientRequestView.as_view(), name='client_request'),
]

sibirmax/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf import settings
from main_menu.views import *


admin.site.site_header = 'SIBIRMAX'
admin.site.index_title = 'Satilik'

router = routers.DefaultRouter()
router.register(r'object_list', RentSalesViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('main_menu.urls')),
    path('api/v1/', include(router.urls)),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('api/v1/object_list/', RentSalesAPIList.as_view()),
    # path('api/v1/object_list/<int:pk>/', RentSalesAPIUpdate.as_view()),
    # path('api/v1/object_detail/<int:pk>/', RentSalesAPIDetailView.as_view()),
]

urlpatterns += i18n_patterns(
    path('', include('main_menu.urls')),
)

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_menu/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class RentSale(models.Model):
    TYPE_CHOICES = [
        ('R', 'Rent'),
        ('S', 'Sale'),
    ]

    PROVINCE_CHOICES = [
        ('ANTAL', 'Antalya')
    ]

    DISTRICT_CHOICES = [
        ('ASKE', 'Akseki'),
        ('AKSU', 'Aksu'),
        ('ALAN', 'Alanya'),
        ('DEMR', 'Demre'),
        ('DESH', 'Döşemealtı'),
        ('ELMA', 'Elmalı'),
        ('FINI', 'Finike'),
        ('GAZI', 'Gazipaşa'),
        ('GUND', 'Gündoğmuş'),
        ('IBRA', 'İbradı'),
        ('KASH', 'Kaş'),
        ('KEME', 'Kemer'),
        ('KEPE', 'Kepez'),
        ('KORK', 'Korkuteli'),
        ('KONY', 'Konyaaltı'),
        ('KUML', 'Kumluca'),
        ('MANA', 'Manavgat'),
        ('MURA', 'Muratpaşa'),
        ('SERI', 'Serik')
    ]

    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default='R')
    city = models.CharField(max_length=5, choices=PROVINCE_CHOICES, default='ANTAL')
    district = models.CharField(max_length=4, choices=DISTRICT_CHOICES, default='KEPE')
    address = models.CharField(max_length=40)
    room = models.IntegerField()
    floor = models.IntegerField()
    square = models.FloatField()
    owner = models.CharField(max_length=100)
    phone_number = models.IntegerField()
    price_in_lira = models.IntegerField()
    created_data = models.DateField(auto_now_add=True)
    updated_time = models.DateField(auto_now=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return (f'Тип объявления: {self.type}, '
                f'Адрес: {self.address}, '
                f'Владелец: {self.owner}, Номер телефона: {self.phone_number}, '
                f'Цена: {self.price_in_lira}, '
                f'Дата создания: {self.created_data}, Дата обновления: {self.updated_time}')


class Picture(models.Model):
    image = models.ImageField(upload_to='images/')
    rentsale = models.ForeignKey(RentSale, on_delete=models.CASCADE, null=True, related_name='pictures')


class ClientRequest(models.Model):
    name = models.CharField(max_length=40, validators=[MinLengthValidator(4)], help_text='Input your name')
    phone = models.IntegerField(help_text='Phone number')
    email = models.EmailField(max_length=254, blank=True, null=True, help_text='Your email (optional)')
    message = models.TextField(blank=True, null=True, help_text='Your message')

    def __str__(self):
        return (f'Имя: {self.name}; '
                f'Телефон: {self.phone}; '
                f'Сообщение: {self.message}')

main_menu/forms.py
from django import forms
from .models import ClientRequest


class ClientRequestForm(forms.ModelForm):
    class Meta:
        model = ClientRequest
        fields = '__all__'
        labels = {
            'name': 'Your name',
            'phone': 'Phone',
            'email': 'Your email',
            'message': 'Your message',
        }
        error_messages = {
            'name': {
                'max_length': 'Input value is too long',
                'min_length': 'Your name must include at least 4 symbols',
                'required': 'Name field cannot be blank',
            }
        }

main_menu/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic.edit import FormView
from rest_framework.viewsets import GenericViewSet
from .forms import ClientRequestForm
from .models import RentSale
from django.views.generic import ListView, DetailView
from rest_framework import mixins
from main_menu.serializer import RentSaleSerializer


class RentSalesViewSet(mixins.CreateModelMixin,
                   mixins.RetrieveModelMixin,
                   mixins.UpdateModelMixin,
                   mixins.DestroyModelMixin,
                   mixins.ListModelMixin,
                   GenericViewSet):
    queryset = RentSale.objects.all()
    serializer_class = RentSaleSerializer


class Menu(ListView):
    template_name = 'main_menu/menu.html'
    model = RentSale


class Sale(ListView):
    template_name = 'main_menu/sale.html'
    model = RentSale
    context_object_name = 'sales'


class Rent(ListView):
    template_name = 'main_menu/rent.html'
    model = RentSale
    context_object_name = 'rents'


class ObjectDetail(DetailView):
    template_name = 'main_menu/detail_view.html'
    model = RentSale


class ClientRequestView(FormView):
    form_class = ClientRequestForm
    template_name = 'main_menu/client_request.html'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super(ClientRequestView, self).form_valid(form)


def contacts(request):
    return render(request, 'main_menu/contacts.html')


def about_us(request):
    return render(request, 'main_menu/about_us.html')


def medical_insurance(request):
    return render(request, 'main_menu/medical_insurance.html')


def resident_card(request):
    return render(request, 'main_menu/resident_card.html')


def terms_of_use(request):
    return render(request, 'main_menu/terms_of_use.html')


def privacy_policy(request):
    return render(request, 'main_menu/privacy_policy.html')


def frequently_asked_questions(request):
    return render(request, 'main_menu/frequently_asked_questions.html')


def citizenship(request):
    return render(request, 'main_menu/citizenship.html')

main_menu/templates/main_menu/about_us.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% translate 'About us' %}{% endblock %}

{% block head_of_content %}
<h1></h1>
{% endblock %}

{% block content %}

<h1>About us</h1>

<div>
    <p>
        Our story started like many good things in life, a spur-of-the-moment kind of idea followed by then proper
        planning, hard work and commitment that can turn a good thing into something great.
    </p>
</div>

<div>
    <p>
        We have come a long way since inception, and at this point, we can humbly say that we have proven to be up
        to the property management challenge and continue to strive to deliver quality services that are priced right.
        We strongly believe in an engagement that benefits all involved parties and is sustainable for the long run.
        We strive to market and rent properties as quickly as possible but do not sacrifice tenant screening and due
        diligence so that only the most suitable candidates are considered.
    </p>
</div>

<div>
    <p>
        Buying, selling or renting a home is likely the largest and most important transaction you’ll ever make.
        That’s why so many trust SibirMax: the most widely recognized real estate brand in the world. For more than
        5 years, SibirMax has been the leading real estate organization in Antalya/Turkey. By providing the best
        5 years, SibirMax has been the leading real estate organization in Antalya/Turkey. By providing the best
        training, administrative and marketing support, brokers and agents are free to focus on what they do best:
        sell, rent, buy real estate.
    </p>
</div>

<div>
    <p>
        Several ancillary services that are aligned with our expertise have been added to our comprehensive
        service offerings to complement our business model.
    </p>
</div>

<div>
    <p>
        We are well staffed to accept more clients and build solid long-term relationships and encourage you to
        contact us for a free quote and allow us the opportunity to partner together.
    </p>
</div>


{% endblock %}

main_menu/templates/main_menu/citizenship.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %} {% translate 'Citizenship' %} {% endblock %}

{% block head_of_content %}
<h1></h1>
{% endblock %}

{% block content %}

<h3>
    Acquisition of Citizenship at Birth
</h3>
<p>
    Acquisition of Turkish citizenship is regulated in two ways: at birth or by later acquisition.
</p>
<p>
    Turkey has not adopted the right to acquire citizenship based on birthplace. Therefore, being born in Turkey will
    not provide any right in terms of citizenship. Citizenship at birth is based on kinship. A person may be a Turkish
    citizen at birth only if one of his/her parents is a Turkish citizen.
</p>
<p>
    Child of a Turkish mother or father is automatically a Turkish citizen. However, adults whose mother and/or father
    is a Turkish citizen but who were not registered to a civil registry office until they turn 18 may be registered
    as a Turkish citizen if it is decided by the Ministry upon an examination that they have acquired Turkish
    citizenship.
</p>

<h3>
    Later Acquisition
</h3>
<p>
    If you fulfill the requirements specified in Turkish Citizenship Law, you can acquire Turkish Citizenship upon the
    decision of the relevant authority. However, the fact that you fulfill the requirements stated does not provide an
    absolute entitlement to citizenship.
</p>
<p>
    <ul>
        <li>
            You can apply for Turkish citizenship if you reside in Turkey with a stateless person identity document or
            as a resident for 5 years without interruption. However, additional conditions such as a good command of
            Turkish, good morals and not being diagnosed with a disease that may constitute hazard to general health
            are also sought.
        </li>
        <li>
            If you are married to a Turkish citizen for at least 3 years and your marriage is sustaining, you can apply
            for Turkish citizenship. If your spouse dies after your application, the requirement of unity of family is
            not sought anymore.
        </li>
        <li>
            Turkish Citizenship Law also contains provisions about acquisition of exceptional citizenship. Provided
            that you do not pose any threat to national security and public order, you may acquire Turkish citizenship
            upon the proposal of the Ministry of the Interior and the decision of the Cabinet.
        </li>
    </ul>
</p>


{% endblock %}

main_menu/templates/main_menu/client_request.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% translate 'Contact Us' %}{% endblock %}

{% block head_of_content %}
<h1></h1>
{% endblock %}

{% block content %}

<div class="ndnrNwU97ucGQrOfz8zQ" style="width: 50%; margin: 0 auto;">
    <form method="POST" class="CrSF_yOD51AMkSJy9hjf" action="{% url 'client_request' %}">
        {% csrf_token %}
        <div class="CrSF_yOD51AMkSJy9hjf">
            <h1 class="od0DN2hUKsFnW55ZBTnF">{% translate 'Contact Us' %}</h1>
            <div class="dOm4Gl8t78fUG9SA6lvl">
                {% for field in form %}
                    <div class="dsrm_formField dlgpBFfaR0zWvrNbWAIS {% if field.errors%} errors {% endif %}" >
                        <label class="dsrm_formLabel" for="id_{{ field.name }}">{{ field.label }}</label>
                        <div class="dsrm_formField__field">
                            <input class="dsrm_inputText dlgpBFfaR0zWvrNbWAIS undefined" type="text"
                                   name="{{ field.name }}" id="id_{{ field.name }}"
                                   placeholder="{{ field.help_text }}">
                        </div>
                    </div>
                {% endfor %}
                <input type="submit" value="Submit"  class="btn btn-primary">
            </div>
        </div>
    </form>
</div>



{% endblock %}

main_menu/templates/main_menu/contacts.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% translate 'Contacts' %}{% endblock %}

{% block head_of_content %}
<h1></h1>
{% endblock %}

{% block content %}

<div>
    <h2>{% translate 'Location' %}</h2>
</div>
<div>
    <div class="contact_row" style="box-sizing: border-box;">
        <div class="contact_column left" >
            <div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3190.9205381311817!2d30.668982315586337!3d36.89224917021169!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14c3902de888ba5f%3A0xc4daec2d5e99a8be!2sMeltem%2C%20Meltem%20Blv.%20No%3A5%2C%2007030%20Muratpa%C5%9Fa%2FAntalya!5e0!3m2!1sru!2str!4v1671468758333!5m2!1sru!2str"
                        width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                        referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
        <div class="contact_column right" style="width: 600px; height: 450px;">
            <div >
                <div><h3>{% translate 'Address' %}</h3></div>
                <div>Antalya, Muratpaşa, 07030</div>
                <div>Meltem, Meltem Blv. No:5</div>
                <div><h3>{% translate 'Company schedule' %}</h3></div>
                <div>{% translate 'Monday–Friday' %}</div>
                <div>{% translate 'Hours' %}</div>
                <div>{% translate '9am–5pm'  %}</div>
                <div><h3>{% translate 'Phone' %}</h3></div>
                <div>+90 (532)-296-25-77</div>
                <div><h3>{% translate 'Email' %}</h3></div>
                <div>mergenh@yahoo.com</div>
            </div>

        </div>
    </div>
</div>




{% endblock %}

main_menu/templates/main_menu/detail_view.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %} {{ object.address }} {% endblock %}

{% block head_of_content %}
<h1>{{object.address}}</h1>
{% endblock %}

{% block content %}

<script>
    window.initializeCarousel=()=>{
        $("carouselExampleFade").carousel({interval:500})
        }
</script>

<div id="listingBodyCon">
    <div id="listingBodyLeftCon">
        <div id="listingDetailsTopCon" class="listingContentBox propertyDetailsSectionCon">
            <div id="listingDetailsTopInnerCon" class="table">
                <div class="leftTableCell">
                    <div>
                        <div style="display: inline-block;">
                            <div id="listingPriceValue">
                                ₺{{ object.price_in_lira }}
                                {% if object.type == 'R' %}
                                    {% translate 'per month' %}
                                {% endif %}
                            </div>
                            <div id="listingNextOpenHouseCon"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="table">
                <div class="listingTopDetailsLeft">
                    <div id="listingAddress" class="unsetH1">
                        {% translate 'Province:' %} {{ object.get_city_display }} <br>
                        {% translate 'Address:' %} {{ object.address }}
                    </div>
                    <div id="listingMLSNum">
                        {% translate 'District:' %} {{object.get_district_display}}
                    </div>
                </div>
                <div class="listingTopDetailsRight">
                    <div class="listingIconsCon">
                        <div id="BedroomIcon" class="listingIconCon">
                            <div class="listingIconNum">{{ object.room }} + 1</div>
                            <div class="listingIcon">
                                <div class="propertyCardBedIcon">
                                    <img src="/media/images/bed_icon.png" alt="bed_icon">
                                </div>
                            </div>
                            <div class="listingIconText">{% translate 'Bedrooms' %}</div>
                        </div>
                        <div id="FloorIcon" class="listingIconCon">
                            <div class="listingIconNum">{{ object.floor }}</div>
                            <div class="listingIcon">
                                <div class="propertyCardBedIcon">
                                    <img src="/media/images/floor_icon.png" alt="floor_icon">
                                </div>
                            </div>
                            <div class="listingIconText">{% translate 'Floor' %}</div>
                        </div>
                        <div id="SquareIcon" class="listingIconCon">
                            <div class="listingIconNum">{{ object.square }}</div>
                            <div class="listingIcon">
                                <div class="propertyCardBedIcon">
                                    <img src="/media/images/square_icon.png" alt="square_icon">
                                </div>
                            </div>
                            <div class="listingIconText">{% translate 'Square' %}</div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div id="listingDetailsTabsCon" class="propertyDetailsSectionCon">
            <div id="listingDetailsTabsBody">
                <div id="listingInfoTab" class="listingTabContent overwriteShowPrint">
                    <div class="propertyDetailsSectionCon" id="PropertyDescription" >
                        <div class="propertyDetailsSectionHeader">{% translate 'Description' %}</div>
                        <div id="propertyDescriptionCon">
                             {{ object.description }}
                        </div>
                    </div>
                    <div class="propertyDetailsSectionCon" id="PropertyData">
                        <div class="propertyDetailsSectionHeader">{% translate 'Data' %}</div>
                        <div class="propertyDetailsSectionContent">
                            <div class="propertyDetailsSectionContentSubCon"
                                 id="propertyDetailsSectionContentSubCon_PropertyType">
                                <div class="propertyDetailsSectionContentValue">{{ object.created_data }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-inner">
        {% for image in object.pictures.all %}
            {% if forloop.first %}
                <div class="carousel-item active">
            {% else %}
                <div class="carousel-item">
            {% endif %}
            <img src="{{ image.image.url }}" alt="">
            </div>
        {% endfor %}
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

{% endblock %}

main_menu/templates/main_menu/frequently_asked_questions.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% translate 'FAQ' %}{% endblock %}

{% block head_of_content %}
<h1></h1>
{% endblock %}

{% block content %}

<h3>Why do visitors love The SibirMax Real Estate Studio?</h3>
<p>
    SibirMax provides real estate buyers, sellers and investors with access trustworthy, up-to-date listings by
    certified professionals from Antalya.
</p>
<p>SibirMax visitors can:
    <ul>
        <li>search properties using their personal criteria;</li>
        <li>learn how SibirMax can help them through the real estate process;</li>
        <li>share their favourite listings with friends and family;</li>
        <li>get notified as soon as a new listing matching their saved search criteria is available;</li>
        <li>use the mortgage calculator and other financial tools to help them determine what they can afford;</li>
        <li>learn more about a property’s neighbourhood with detailed demographic information for each listing.</li>
    </ul>
</p>

{% endblock %}

main_menu/templates/main_menu/medical_insurance.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %} {% translate 'Medical insurance' %} {% endblock %}

{% block head_of_content %}
<h1></h1>
{% endblock %}

{% block content %}

<h3>
    Healthcare in Turkey for Expats and Foreigners
</h3>
<p>
    Every year, thousands of patients from all over the world come to Turkey to get medical services. The success of
    the healthcare system has increased in recent years. It’s easy to find well-educated and English-speaking
    medical professionals in Turkey.
</p>
<p>
    A recent study published in The Lancet ranks Turkey’s healthcare system 60th among 195 countries in the world.
    The increasing number of medical schools and specialists in the country is a sign of this. If you’re planning
    to live in Turkey, it’s time that you become acquainted with the healthcare system in the country.
</p>


<h3>
    The Healthcare System In Turkey
</h3>
<p>
    Healthcare in Turkey consists of both public and private health services. The Ministry of Health (MOH),
    universities, and the private sector provide healthcare services. Foreigners and expats living in Turkey can apply
    for health benefits in two ways;  Universal Health Insurance and private health insurance. The European Health
    Insurance Card is not efficient in Turkey. Also, health insurance is compulsory in Turkey. Thus, you’ll need
    health insurance to get residency or work permits.
</p>


<h3>
    Universal Health Insurance in Turkey
</h3>
<p>
    Universal Health Insurance covers most health issues such as emergencies, pregnancy, and illnesses. Social
    Security Institution (SGK) administers general healthcare in Turkey.  To do so, you need to contact the nearest
    social security center. If you enroll in this scheme, you can also enjoy discounts in private hospitals.
    But, note that state hospitals are sometimes very crowded.
</p>
<p>
    <strong> How Can You Apply for Universal Health Insurance</strong>
</p>
<p>
    If you’ve lived in Turkey for one year, you’re eligible to apply. You can access all the medical care with a
    monthly fee. The monthly premium for 2021 is about ₺850, and it changes every year. You can get updated
    information from the application centers for healthcare in Turkey for foreigners. There are approximately 600
    social security centers in the country.  When you apply for SGK, your spouse and children under 18 can benefit
    from healthcare for foreigners.
</p>
<p>
    Treatment services covered by SGK:
</p>
<ul>
    <li>Inpatient and outpatient services</li>
    <li>Occupational accidents and diseases</li>
    <li>Pregnancy, birth, and related expenses</li>
    <li>Discounts in private hospitals and clinics, etc.</li>
    <li>Infectious diseases</li>
    <li>Preventive health services</li>
    <li>Treatment costs of foreigners and their dependents, except for chronic diseases</li>
</ul>


<h3>
    Private Health Insurance in Turkey</h3>
<p>
    You can get private health insurance in Turkey by paying a monthly fee to an insurance company. Private health
    insurance offers more benefits than SGK does. These are shorter waiting times, the highest quality of care, and
    fewer unexpected expenses. Also, it’s easy to find more English-speaking doctors in private hospitals. So, you may
    prefer a private healthcare option rather than SGK.
</p>
<p>
    Treatment services covered by private insurance:
</p>
<ul>
    <li>Medical examination costs</li>
    <li>Costs for diagnostic examinations</li>
    <li>Medication costs</li>
    <li>Hospital services (operation, anesthesia, medication, laboratory, radiology, etc.)</li>
    <li>Room, bed, meal, and accompanying expenses during hospitalization.</li>
    <li>Corneal, kidney, pancreas, liver, heart, lung transplantation.</li>
    <li>Chemotherapy, radiation therapy, dialysis</li>
    <li>Diagnostic biochemical, microbiological, pathological, radiological, and imaging tests during hospitalization.</li>
    <li>Costs of artificial limbs in case of loss of limbs due to an accident or illness</li>
    <li>Postoperative physical therapy</li>
    <li>Medical treatments for less than 24 hours (food poisoning, simple burn treatments)</li>
    <li>Treatments in intensive care</li>
    <li>Therapies related to teeth and nose caused by a traffic accident</li>
</ul>

{% endblock %}

main_menu/templates/main_menu/menu.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %} {% translate 'Menu' %} {% endblock %}

{% block head_of_content %}
{% endblock %}

{% block content %}

<div id="homeHeaderCon" class="fullWidth"
     style="background-image: url('/media/images/background.jpg');
     background-repeat: no-repeat;
     background-attachment: fixed;
     background-size: 100% 100%;">
    <div id="homeHeaderInnerCon">
        <div id="homeHeaderTitle" class="customHeaderImageText">
            {% translate 'Find homes and apartments from trusted SibirMax' %}</div>
    </div>
</div>

<div id="homeHeaderFooterCon" class="fullWidth">
    <div><strong>{% translate 'Need help finding a realtor?' %}</strong></div>
    <a class="whiteRoundedBtn btn" href="{% url 'client_request' %}" id="whiteRoundedBtn">
        {% translate 'Get Started' %}</a>
</div>

<div class="fullWidth">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1">
            </button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                    aria-label="Slide 2">
            </button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                    aria-label="Slide 3">
            </button>
        </div>
        <div class="carousel-inner">
            <h1 class="NAC_WhyUseRealtorPageTitleH1" style="font-size:30px" >
            {% translate 'Why use SibirMax Real Estate Agency?' %}
            </h1>
            <div class="carousel-item active">
                <img src="/media/images/slide_photo_1.png" class="d-block w-100" alt="slide_photo_1">
                <div class="carousel-caption d-none d-md-block">
                    <h2 class="carouselTextCon"><strong>Expertise</strong></h2>
                    <p class="carouselTextCon"><strong>
                        By working with SibirMax, you’ll be able to navigate complicated situations like a pro.
                        SibirMax have the expertise required to help strategize, negotiate and achieve the best
                        outcomes possible. Plus, they’ll provide expert guidance throughout the entire home buying
                        and selling journey.</strong>
                    </p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/media/images/slide_photo_2.png" class="d-block w-100" alt="slide_photo_2">
                <div class="carousel-caption d-none d-md-block">
                    <h2 class="carouselTextCon"><strong>Knowledge</strong></h2>
                    <p class="carouselTextCon"><strong>
                        With valuable real estate market knowledge, SibirMax work to ensure you’re getting objective
                        and accurate information when it comes to buying or selling your home.
                    </strong>
                    </p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/media/images/slide_photo_3.png" class="d-block w-100" alt="slide_photo_3">
                <div class="carousel-caption d-none d-md-block">
                    <h2 class="carouselTextCon"><strong>Dedication</strong></h2>
                    <p class="carouselTextCon"><strong>
                        SibirMax will be on your team and is committed to protecting your interests. As you navigate
                        this complex process, they’ll be with you every step of the way.
                    </strong></p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

{% endblock %}